version: '3'
services:
    raspberrypi3-homeassistant:
        container_name: home-assistant
        network_mode: 'host'
        volumes:
            - '/home/pi/homeassistant:/config'
            - '/etc/localtime:/etc/localtime:ro'
        devices:
            - /dev/serial/by-id/usb-0658_0200-if00
            #- /dev/ttyAMA0
            #- /dev/ttyACM0
            - /dev/vcio
        #image: home-assistant-mine
        image: homeassistant/home-assistant:0.111.4
        #0.107.7 
        #0.98.4 
        restart: "unless-stopped"