- platform: switch
  name: Laundry
  entity_id: switch.laundry
- platform: switch
  name: Pantry
  entity_id: switch.pantry
- platform: switch
  name: Mud
  entity_id: switch.mud
- platform: switch
  name: Garage Entry
  entity_id: switch.garage_entry
- platform: switch
  name: Garage
  entity_id: switch.garage
