- platform: group
  name: Family Room Lights
  entities:
    - light.family_south
    - light.family_west
    - light.family_east
    - light.kitchenette_cans
    - light.kitchenette_cabinet
    - light.kitchenette_pendant
    - light.stairway
- platform: group
  name: Basement Lights
  entities:
    - light.family_south
    - light.family_west
    - light.family_east
    - light.kitchenette_cans
    - light.kitchenette_pendant
    - light.kitchenette_cabinet
    - light.stairway
    - light.play
    - light.guest
    - light.laundry
    - light.basement_bathroom
- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_sink
    - light.kitchen_cans
    - light.nook
- platform: group
  name: Upstairs Lights
  entities:
    - light.entry
    - light.master_bath_toilet
    - light.master_bath_sink
    - light.master_bath_shower
    - light.dining
    - light.mud
    - light.pantry
    - light.garage_entry
    #- light.living_room_fan_light
    #- light.magnus_fan_light
    #- light.master_bedroom_fan_light
    - light.kitchen_sink
    - light.kitchen_cans
    - light.nook
- platform: group
  name: Living Room Lights
  entities:
    #- light.living_room_fan_light
    - light.entry
- platform: group
  name: Master Bath Lights
  entities:
    - light.master_bath_toilet
    - light.master_bath_sink
    - light.master_bath_shower
- platform: group
  name: Common Area Lights
  entities:
    - light.family_south
    - light.family_west
    - light.family_east
    - light.kitchenette_cans
    - light.kitchenette_pendant
    - light.kitchenette_cabinet
    - light.stairway
    - light.entry
    - light.dining
    #- light.living_room_fan_light
- platform: group
  name: All Lights
  entities:
    - light.family_south
    - light.family_west
    - light.family_east
    - light.kitchenette_cans
    - light.kitchenette_pendant
    - light.kitchenette_cabinet
    - light.stairway
    - light.guest
    - light.play
    #- light.magnus_fan_light
    #- light.master_bedroom_fan_light
    - light.master_bath_toilet
    - light.master_bath_sink
    - light.master_bath_shower
    - light.hall_bath
    - light.basement_bathroom
    - light.entry
    - light.dining
    - light.mud
    - light.pantry
    - light.laundry
    - light.garage
    - light.garage_entry
    #- light.living_room_fan_light
- platform: group
  name: Outside Lights
  entities:
    - light.rear_porch
    - light.front_outside
    - light.garage