- platform: group
  name: Family Room Lights
  entities:
    - light.family_south
    - light.family_west
    - light.family_east
    - light.kitchenette_cans
    - light.kitchenette_cabinet
- platform: group
  name: Basement Lights
  entities:
    - light.family_south
    - light.family_west
    - light.family_east
    - light.kitchenette_cans
    - light.kitchenette_pendant
    - light.kitchenette_cabinet
    - light.stairway
    - light.play
    - light.twin
- platform: group
  name: Mainfloor Lights
  entities:
    - light.entry
    - light.mb_toilet
    - light.mb_sink
    - light.mb_shower
    - light.dining
    - light.mud
    - light.pantry
    - light.garage
    - light.garage_entry
- platform: group
  name: Master Bath Lights
  entities:
    - light.mb_toilet
    - light.mb_sink
    - light.mb_shower
- platform: group
  name: All Lights
  entities:
    - light.family_south
    - light.family_west
    - light.family_east
    - light.kitchenette_cans
    - light.kitchenette_pendant
    - light.kitchenette_cabinet
    - light.stairway
    - light.twin
    - light.play
    - light.mb_toilet
    - light.mb_sink
    - light.mb_shower
    - light.entry
    - light.dining
    - light.basement_bathroom
    - light.mud
    - light.pantry
    - light.laundry
    - light.garage
    - light.garage_entry
- platform: group
  name: Outside Lights
  entities:
    - light.rear_porch
    - light.front_outside