- alias: "Hall Bathroom Occupied Light"
  trigger: 
    - platform: state
      entity_id: light.hall_bath
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.hall_bathroom_occupied

- alias: "Hall Bathroom Not Occupied Light"
  trigger: 
    - platform: state
      entity_id: light.hall_bath
      to: 'off'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.hall_bathroom_occupied