- platform: template
  sensors:
    family_room_right:
      friendly_name: "Family Room Right Blind"
      value_template: "{{ state_attr('zwave.family_room_right_blind','battery_level') }}"
      unit_of_measurement: "%"
    family_room_left:
      friendly_name: "Family Room Left Blind"
      value_template: "{{ state_attr('zwave.family_room_left_blind','battery_level') }}"
      unit_of_measurement: "%"
    guest:
      friendly_name: "Guest Room Blind"
      value_template: "{{ state_attr('zwave.guest_room_blind','battery_level') }}"
      unit_of_measurement: "%"
    master_right:
      friendly_name: "Master Right Blind"
      value_template: "{{ state_attr('zwave.master_right_blind','battery_level') }}"
      unit_of_measurement: "%"
    master_left:
      friendly_name: "Master Left Blind"
      value_template: "{{ state_attr('zwave.master_left_blind','battery_level') }}"
      unit_of_measurement: "%"
    girl_left:
      friendly_name: "Girl Left Blind"
      value_template: "{{ state_attr('zwave.girl_left_blind','battery_level') }}"
      unit_of_measurement: "%"
    girl_right:
      friendly_name: "Girl Right Blind"
      value_template: "{{ state_attr('zwave.girl_right_blind','battery_level') }}"
      unit_of_measurement: "%"
    boy_left:
      friendly_name: "Boy Left Blind"
      value_template: "{{ state_attr('zwave.boy_left_blind','battery_level') }}"
      unit_of_measurement: "%"
    boy_right:
      friendly_name: "Boy Right Blind"
      value_template: "{{ state_attr('zwave.boy_right_blind','battery_level') }}"
      unit_of_measurement: "%"
    living_room_left:
      friendly_name: "Living Room Left Blind"
      value_template: "{{ state_attr('zwave.living_room_left_blind','battery_level') }}"
      unit_of_measurement: "%"
    living_room_right:
      friendly_name: "Living Room Right Blind"
      value_template: "{{ state_attr('zwave.living_room_right_blind','battery_level') }}"
      unit_of_measurement: "%"
    dining_room_left:
      friendly_name: "Dining Room Left Blind"
      value_template: "{{ state_attr('zwave.dining_room_left_blind','battery_level') }}"
      unit_of_measurement: "%"
    dining_room_right:
      friendly_name: "Dining Room Right Blind"
      value_template: "{{ state_attr('zwave.dining_room_right_blind','battery_level') }}"
      unit_of_measurement: "%"
    kitchen:
      friendly_name: "Kitchen Blind"
      value_template: "{{ state_attr('zwave.kitchen_blind','battery_level') }}"
      unit_of_measurement: "%"
    dining_room_center:
      friendly_name: "Dining Room Center Blind"
      value_template: "{{ state_attr('zwave.dining_room_center_blind','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_1:
      friendly_name: "Controller 1 Battery"
      value_template: "{{ state_attr('zwave.family_room_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_2:
      friendly_name: "Controller 2 Battery"
      value_template: "{{ state_attr('zwave.playroom_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    play:
      friendly_name: "Play Room"
      value_template: "{{ state_attr('zwave.play_room_blind','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_5:
      friendly_name: "Controller 5 Battery"
      value_template: "{{ state_attr('zwave.@master_off_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_6:
      friendly_name: "Controller 6 Battery"
      value_template: "{{ state_attr('zwave.master_bedroom_blinds_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_7:
      friendly_name: "Controller 7 Battery"
      value_template: "{{ state_attr('zwave.master_bedroom_blinds_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_8:
      friendly_name: "Controller 8 Battery"
      value_template: "{{ state_attr('zwave.kitchen_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_9:
      friendly_name: "Controller 9 Battery"
      value_template: "{{ state_attr('zwave.9_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_10:
      friendly_name: "Controller 10 Battery"
      value_template: "{{ state_attr('zwave.master_common_area_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_11:
      friendly_name: "Controller 11 Battery"
      value_template: "{{ state_attr('zwave.11_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_12:
      friendly_name: "Controller 12 Battery"
      value_template: "{{ state_attr('zwave.girl_room_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_13:
      friendly_name: "Controller 13 Battery"
      value_template: "{{ state_attr('zwave.13_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_14:
      friendly_name: "Controller 14 Battery"
      value_template: "{{ state_attr('zwave.boy_room_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_15:
      friendly_name: "Controller 15 Battery"
      value_template: "{{ state_attr('zwave.15_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_16:
      friendly_name: "Controller 16 Battery"
      value_template: "{{ state_attr('zwave.16_blind_controller','battery_level') }}"
      unit_of_measurement: "%"
    batt_controller_4:
      friendly_name: "Controller 4 Battery"
      value_template: "{{ state_attr('zwave.master_common_area_blind_controller','battery_level') }}"
      unit_of_measurement: "%"