- platform: template
  sensors:
    dryer_power:
      friendly_name: "Dryer Power"
      value_template: "{{ state_attr('switch.dryer','current_power_w') }}"
    washing_machine_power:
      friendly_name: "Washing Machine Power"
      value_template: "{{ state_attr('switch.washing_machine','current_power_w') }}"