- alias: "Custom Alexa Notification"
  trigger:
    - platform: state
      entity_id: input_boolean.execute_alexa_notification
      to: 'on'
  action:
    - service: notify.alexa_media
      data:
        target: 
          - media_player.family_room
        #title: "My title for Echo show"
        data:
          type: announce
          #method: all
      data_template:
        message: "{{ states('input_text.alexa_announcement_text') }}"
    - service: input_boolean.toggle
      entity_id: input_boolean.execute_alexa_notification
      