- alias: Bathroom at Night Notification
  trigger:
    - platform: state
      entity_id: input_boolean.hall_bathroom_occupied
      to: 'on'
      for: '00:05:00'
    - platform: state
      entity_id: input_boolean.basement_bathroom_occupied
      to: 'on'
      for: '00:05:00'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '20:00:00'
      - condition: time
        before: '08:00:00'
  action:
    - service: notify.ios_heidis_iphone_7
      data:
        data_template:
          message: "{{ trigger.entity_id.title() }} has someone in it for more than 5 minutes" #|replace("_"," ")|replace(" Occupied","")
    - service: notify.alexa_media
      data:
        target: 
          - media_player.craig_s_alexa_apps
        data:
          type: push
        data_template:
          message: "{{ trigger.entity_id.title() }} has someone in it for more than 5 minutes" #|replace("_"," ")|replace(" Occupied","")

- alias: Bathroom Anytime Notification
  trigger:
    - platform: state
      entity_id: input_boolean.hall_bathroom_occupied
      to: 'on'
      for: '00:15:00'
    - platform: state
      entity_id: input_boolean.basement_bathroom_occupied
      to: 'on'
      for: '00:15:00'
  action:
    - service: notify.ios_heidis_iphone_7
      data_template:
        data:
          message: "{{ trigger.entity_id.title() }} has someone in it for more than 15 minutes" #|replace("_"," ")|replace(" Occupied","")
    - service: notify.alexa_media
      data:
        target: 
          - media_player.craig_s_alexa_apps
        data:
          type: push
        data_template:
          message: "{{ trigger.entity_id.title() }} has someone in it for more than 15 minutes" #|replace("_"," ")|replace(" Occupied","")

