- alias: Master Bathroom Fan Timer
  trigger:
    - platform: state
      entity_id: light.master_bath_lights
      to: 'off'
      for:
        minutes: 15
  action:
    service: switch.turn_off
    entity_id: switch.master_bathroom_fan

- alias: Master Bathroom Fan Timer
  trigger:
    - platform: state
      entity_id: switch.master_bathroom_fan
      to: 'on'
      for:
        minutes: 60
  action:
    service: switch.turn_off
    entity_id: switch.master_bathroom_fan

- alias: Basement Bathroom Fan Timer
  trigger:
    - platform: state
      entity_id: light.basement_bathroom
      to: 'off'
      for:
        minutes: 15
  action:
    service: switch.turn_off
    entity_id: switch.basement_bathroom_fan

- alias: Basement Bathroom Fan Timer Long
  trigger:
    - platform: state
      entity_id: switch.basement_bathroom_fan
      to: 'on'
      for:
        minutes: 60
  action:
    service: switch.turn_off
    entity_id: switch.basement_bathroom_fan

- alias: Hall Bathroom Fan Timer
  trigger:
    - platform: state
      entity_id: light.hall_bath
      to: 'off'
      for:
        minutes: 15
  action:
    service: switch.turn_off
    entity_id: switch.hall_bath_fan

- alias: Hall Bathroom Fan Timer Long
  trigger:
    - platform: state
      entity_id: switch.hall_bath_fan
      to: 'on'
      for:
        minutes: 60
  action:
    service: switch.turn_off
    entity_id: switch.hall_bath_fan