- alias: Bathroom Unoccupied Fan Off
  trigger:
    - platform: state
      entity_id: light.master_bath_lights
      to: 'off'
      for: '00:15:00'
  action:
    service: switch.turn_off
    entity_id: switch.master_bathroom_fan

- alias: Basement Bathroom Fan Timer
  trigger:
    - platform: state
      entity_id: light.basement_bathroom
      to: 'off'
      for: '00:15:00'
  action:
    service: switch.turn_off
    entity_id: switch.basement_bathroom_fan

- alias: Hall Bathroom Fan Timer
  trigger:
    - platform: state
      entity_id: light.hall_bath
      to: 'off'
      for: '00:15:00'
  action:
    service: switch.turn_off
    entity_id: switch.hall_bath_fan
    
- alias: Fan Timers
  trigger:
    - platform: state
      entity_id: switch.master_bathroom_fan
      to: 'on'
      for: '00:60:00'
    - platform: state
      entity_id: switch.basement_bathroom_fan
      to: 'on'
      for: '00:60:00'
    - platform: state
      entity_id: switch.hall_bath_fan
      to: 'on'
      for: '00:60:00'
  action:
    service: switch.turn_off
    data_template:
      # Whichever entity triggers the automation we want to turn off THAT entity, not the others.
      entity_id: "{{ trigger.entity_id }}"

