- alias: Hall Bathroom at Night Notification
  trigger:
    - platform: state
      entity_id: input_boolean.hall_bathroom_occupied
      to: 'on'
      for:
        minutes: 5
#    - platform: time
#      at: '18:59:12'

#Only operate if it's between 2000-0800
  condition:
    condition: and
    conditions:
      - condition: time
        after: '20:00:00'
      - condition: time
        before: '08:00:00'
  action:
    - service: notify.ios_heidis_iphone_7
      data:
        message: "Hall Bathroom: Occupied >5m"
    - service: notify.alexa_media
      data:
        target: 
          - media_player.craig_s_alexa_apps
          #- media_player.heidi_s_alexa_apps
        #title: "My title for Echo show"
        data:
          type: push
          #method: all
        message: "Hall Bathroom has someone in it for more than 5 minutes"

- alias: Hall Bathroom Anytime Notification
  trigger:
    - platform: state
      entity_id: input_boolean.hall_bathroom_occupied
      to: 'on'
      for:
        minutes: 15
#    - platform: time
#      at: '18:59:12'
  action:
    - service: notify.ios_heidis_iphone_7
      data:
        message: "Hall Bathroom: Occupied >15m"
    - service: notify.alexa_media
      data:
        target: 
          - media_player.craig_s_alexa_apps
          #- media_player.heidi_s_alexa_apps
        #title: "My title for Echo show"
        data:
          type: push
          #method: all
        message: "Hall Bathroom has someone in it for more than 15 minutes"

- alias: Basement Bathroom at Night Notification
  trigger:
    - platform: state
      entity_id: input_boolean.basement_bathroom_occupied
      to: 'on'
      for:
        minutes: 5
#    - platform: time
#      at: '18:59:12'

#Only operate if it's between 2000-0800
  condition:
    condition: and
    conditions:
      - condition: time
        after: '20:00:00'
      - condition: time
        before: '08:00:00'
  action:
    - service: notify.ios_heidis_iphone_7
      data:
        message: "Basement Bathroom: Occupied >5m"
    - service: notify.alexa_media
      data:
        target: 
          - media_player.craig_s_alexa_apps
          #- media_player.heidi_s_alexa_apps
        #title: "My title for Echo show"
        data:
          type: push
          #method: all
        message: "Basement Bathroom has someone in it for more than 5 minutes"

- alias: Basement Bathroom Anytime Notification
  trigger:
    - platform: state
      entity_id: input_boolean.basement_bathroom_occupied
      to: 'on'
      for:
        minutes: 15
#    - platform: time
#      at: '18:59:12'

#Only operate if it's between 2000-0800
  action:
    - service: notify.ios_heidis_iphone_7
      data:
        message: "Basement Bathroom: Occupied >15m"
    - service: notify.alexa_media
      data:
        target: 
          - media_player.craig_s_alexa_apps
          #- media_player.heidi_s_alexa_apps
        #title: "My title for Echo show"
        data:
          type: push
          #method: all
        message: "Basement Bathroom has someone in it for more than 15 minutes"
