- alias: "Remind me to put the kids to bed"
  initial_state: 'off'
  trigger:
    - platform: time
      at: '20:00:00'
  action:
    - service: notify.alexa_media
      data:
        target: 
          - media_player.family_room
          - media_player.living_room_2
          - media_player.nora_room
          - media_player.magnus_room
        #title: "My title for Echo show"
        data:
          type: announce
          #method: all
        message: "Time for Nora and Magnus to go to bed"

- alias: "Test announcement"
  initial_state: 'off'
  trigger:
    - platform: time
      at: '19:32:00'
  action:
    - service: notify.alexa_media
      data:
        target: 
          - media_player.family_room
          - media_player.living_room_2
        #title: "My title for Echo show"
        data:
          type: announce
          #method: all
        message: "This is your reminder"