- alias: "Announce Family Calendar"
  initial_state: 'on'
  trigger:
   - platform: state
     entity_id: calendar.family_calendar
  action:
    - service: notify.alexa_media
      data:
        target: 
          - media_player.everywhere
        #title: "My title for Echo show"
        data:
          type: announce
          #method: all
        message: "{{ trigger.entity_id.data.summary }}" 