- alias: Bedtime for Boy Blinds
  trigger:
    - platform: time
      at: '18:59:12'
  action:
    service: cover.close_cover
    entity_id: cover.boy_blinds

- alias: Bedtime for Girl Blinds
  trigger:
    - platform: time
      at: '18:59:12'
  action:
    service: cover.close_cover
    entity_id: cover.girl_blinds

- alias: Close blinds automatically
  trigger:
   - platform: numeric_state
     entity_id: sun.sun
     value_template: '{{ state.attributes.elevation }}'
     below: 0
   - platform: time
     at: '20:30:00'
  action:
    - service: cover.close_cover
      entity_id: cover.east_blinds
    - delay: '00:00:15'
    - service: cover.close_cover
      entity_id: cover.west_blinds

- alias: Morning blinds open automatically
  trigger:
   - platform: time
     at: '07:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.house_wakeup_covers