- alias: Turn Garage Entry On
  trigger:
    - platform: state
      entity_id: light.garage
      to: 'on'
    - platform: state
      entity_id: light.mud
      to: 'on'
    - platform: state
      entity_id: light.pantry
      to: 'on'
  action:
    service: light.turn_on
    entity_id: light.garage_entry

- alias: Turn Garage Entry Off
  trigger:
    - platform: state
      entity_id: light.garage
      to: 'off'
    - platform: state
      entity_id: light.mud
      to: 'off'
    - platform: state
      entity_id: light.pantry
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.garage
        state: 'off'
      - condition: state
        entity_id: light.pantry
        state: 'off'
      - condition: state
        entity_id: light.mud
        state: 'off'
  action:
    service: light.turn_off
    entity_id: light.garage_entry