- alias: "Notify at startup"
  initial_state: 'on'
  trigger:
   - platform: homeassistant
     event: start
  action:
    - service: notify.mobile_app_pixel_3a
      data:
        title: 'HomeAssistant'
        message: 'HomeAssistant is starting up'
        data:
          color: '#E0FFFF' #cyan
          tag: homeassistant-core

- alias: "Notify at stop"
  initial_state: 'on'
  trigger:
   - platform: homeassistant
     event: shutdown
  action:
    - service: notify.mobile_app_pixel_3a
      data:
        title: 'HomeAssistant'
        message: 'HomeAssistant is shutting down'
        data:
          color: '#E0FFFF' #cyan
          tag: homeassistant-core

- alias: "Z-wave Network is starting"
  trigger:
    platform: event
    event_type: zwave.network_start
  action:
    - service: notify.mobile_app_pixel_3a
      data:
        title: 'HomeAssistant'
        message: 'Z-Wave Network Starting'
        data:
          color: '#E0FFFF' #cyan
          tag: zwave

- alias: "Z-wave Network is stopping"
  trigger:
    platform: event
    event_type: zwave.network_stop
  action:
    - service: notify.mobile_app_pixel_3a
      data:
        title: 'HomeAssistant'
        message: 'Z-Wave Network Stopping'
        data:
          color: '#E0FFFF' #cyan
          tag: zwave

- alias: "Z-wave Network is ready"
  trigger:
    platform: event
    event_type: zwave.network_ready
  action:
    - service: notify.mobile_app_pixel_3a
      data:
        title: 'HomeAssistant'
        message: 'Z-Wave Network Ready'
        data:
          color: '#E0FFFF' #cyan
          tag: zwave
    - service: automation.turn_on
      entity_id:
        - automation.motion_detected_in_the_garage