- alias: "Dryer has started"
  trigger:
    - platform: numeric_state
      entity_id: switch.dryer
      value_template: "{{ state.attributes.current_power_w }}"
      above: 0
  action:
    - service: homeassistant.turn_on
      entity_id: automation.dryer_has_stopped

- alias: "Dryer has stopped"
  initial_state: 'off'
  trigger:
    - platform: numeric_state
      entity_id: switch.dryer
      value_template: "{{ state.attributes.current_power_w }}"
      below: 1
  condition:
    - condition: template # only notify once every 12 minutes at most
      value_template: "{{ ( as_timestamp(now()) - as_timestamp(state_attr('automation.dryer_has_started', 'last_triggered')) |int(0) ) > 720 }}"
  action:
    - service: homeassistant.turn_off
      entity_id: automation.dryer_has_stopped
    - service: notify.alexa_media
      data:
        target: 
          - media_player.craig_s_alexa_apps
          #- media_player.heidi_s_alexa_apps
        #title: "My title for Echo show"
        data:
          type: push
          #method: all
        message: "Dryer is done"
    #- service: notify.discord_bot
    #  data:
    #    target: !secret discord_notify_channel_id_general
    #    message: Dryer is done  
    #    data:
    #      tag: 'dryer-stopped'

- alias: "Washer has started"
  trigger:
    - platform: numeric_state
      entity_id: switch.washing_machine
      value_template: "{{ state.attributes.current_power_w }}"
      above: 0
  action:
    - service: homeassistant.turn_on
      entity_id: automation.washer_has_stopped

- alias: "Washer has stopped"
  initial_state: 'off'
  trigger:
    - platform: numeric_state
      entity_id: switch.washing_machine
      value_template: "{{ state.attributes.current_power_w }}"
      below: 1
  action:
    - service: homeassistant.turn_off
      entity_id: automation.washer_has_stopped
#    - service: notify.ios_heidis_iphone_7
#      data:
#        message: "Washer: Done"
#    - service: notify.alexa_media
#      data:
#        target: 
#          - media_player.everywhere
#        #title: "My title for Echo show"
#        data:
#          type: announce
#          #method: all
#        message: "The Washing machine has finished."
#    - delay: '00:00:03'
    - service: notify.mobile_app_pixel_3a
      data:
        title: 'Laundry'
        message: 'Washer is Done'
        data:
          color: '#E0FFFF' #cyan
    - service: notify.mobile_app_heidi_s_iphone_11
      data:
        title: 'Laundry'
        message: 'Washer is Done'
#    - service: notify.alexa_media
#      data:
#        target: 
#          #- media_player.craig_s_alexa_apps
#          - media_player.heidi_s_alexa_apps
#        #title: "My title for Echo show"
#        data:
#          type: push
#          #method: all
#        message: "Washer is done"        
    #- service: notify.discord_bot
    #  data:
    #    target: !secret discord_notify_channel_id_general
    #    message: Washer is done  
    #    data:
    #      tag: 'washer-stopped'