- alias: Kitchen Cans follow sink light (ON)
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.kitchen_sink
  condition:
    condition: and  # 'when light' condition: before sunset and after sunrise - equivalent to a state condition on `sun.sun` of `above_horizon`
    conditions:
    - condition: sun
      before: sunset
    - condition: sun
      after: sunrise
  action:
    service: light.turn_on
    data:
      entity_id: 
        - light.kitchen_cans
        - light.nook
    data_template: 
      brightness: "{{ state_attr('light.kitchen_sink', 'brightness') }}"


- alias: Kitchen Cans Light Follow Mode of Sink light (OFF)
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.kitchen_sink
      to: 'off'
  action:
    service: light.turn_off
    entity_id: 
        - light.kitchen_cans
        - light.nook

- alias: Stairway Light Follows Entry (ON)
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.entry
  action:
    service: light.turn_on
    data:
      entity_id: 
        - light.stairway    
    data_template: 
      brightness: "{{ state_attr('light.entry', 'brightness') }}"

- alias: Entry Light Follows Stairway (ON)
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.stairway
  action:
    service: light.turn_on
    data:
      entity_id: 
        - light.entry    
    data_template: 
      brightness: "{{ state_attr('light.stairway', 'brightness') }}"