- alias: "Motion Detected in the Garage"
  initial_state: 'off'
  trigger:
    - platform: numeric_state
      entity_id: sensor.garage_motion
      above: 7
  condition:
    - condition: template # only notify once every 5 minutes at most
      value_template: "{{ ( as_timestamp(now()) - as_timestamp(state_attr('automation.motion_detected_in_the_garage', 'last_triggered')) |int(0) ) > 300 }}"      
  action:
    - service: notify.alexa_media
      data:
        target: 
          - media_player.everywhere
        #title: "My title for Echo show"
        data:
          type: announce
          #method: all
        message: "Motion Detected in the Garage"

- alias: "Motion Detected in the Laundry"
#This is primarily used for testing
  initial_state: 'off'
  trigger:
    - platform: numeric_state
      entity_id: sensor.laundry_motion
      above: 7
  action:
    - service: notify.alexa_media
      data:
        target: 
          - media_player.everywhere
        #title: "My title for Echo show"
        data:
          type: announce
          #method: all
        message: "Motion Detected in the Laundry"