- alias: Motion Detected at the Front Door (Ring)
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion
      to: 'Detected'
  action:
    - service: notify.alexa_media
      data:
        target: 
          - media_player.craig_s_alexa_apps
          - media_player.heidi_s_alexa_apps
        #title: "My title for Echo show"
        data:
          type: push
          #method: all
          message: "Front Door Motion"
    - service: notify.alexa_media
      data:
        target: 
          - media_player.everywhere
        #title: "My title for Echo show"
        data:
          type: announce
          #method: all
        message: "Motion Detected at the front door"
    - service: downloader.download_file
      data_template:
        url: "{{ state_attr('camera.front_door', 'video_url') }}"
        subdir: "{{state_attr('camera.front_door', 'friendly_name')}}"
        filename: "{{state_attr('camera.front_door', 'friendly_name')}}"

- alias: Ding Detected at the Front Door (Ring)
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      to: 'Detected'
  action:
    - service: notify.alexa_media
      data:
        target: 
          - media_player.craig_s_alexa_apps
          - media_player.heidi_s_alexa_apps
        #title: "My title for Echo show"
        data:
          type: push
          #method: all
        message: "Front Door doorbell"
    - service: notify.alexa_media
      data:
        target: 
          - media_player.everywhere
        #title: "My title for Echo show"
        data:
          type: announce
          #method: all
        message: "Someone is at the front door"

