- alias: "Started Snowing"
  initial_state: 'on'
  trigger:
   - platform: state
     entity_id: weather.home
     to: 'snowy'
  action:
    - service: homeassistant.turn_on
      entity_id: automation.stopped_snowing
    - service: notify.alexa_media
      data:
        target: 
          - media_player.craig_s_alexa_apps
        #title: "My title for Echo show"
        data:
          type: push
          #method: all
        message: "Snow began"

- alias: "Stopped Snowing"
  initial_state: 'off'
  trigger:
   - platform: state
     entity_id: weather.home
     from: 'snowy'
  action:
    - service: homeassistant.turn_off
      entity_id: automation.stopped_snowing
    - service: notify.alexa_media
      data:
        target: 
          - media_player.craig_s_alexa_apps
        #title: "My title for Echo show"
        data:
          type: push
          #method: all
        message: "Snow stopped"